double *monomial_value_2d ( int n, int ex, int ey, double x[], double y[] );
double *r8vec_copy_new ( int n, double a1[] );
double r8vec_dot_product ( int n, double a1[], double a2[] );
void timestamp ( );
double triangle_unit_monomial ( int ex, int ey );
double triangle_unit_volume ( );
int twb_rule_n ( int strength );
double *twb_rule_w ( int strength );
double *twb_rule_x ( int strength );
double *twb_rule_y ( int strength );
