int *i4vec_uniform_ab_new ( int n, int a, int b, int &seed );
double *monomial_value ( int m, int n, int e[], double x[] );
double r8vec_sum ( int n, double a[] );
double *r8mat_uniform_ab_new ( int m, int n, double a, double b, int &seed );
double square01_area ( );
double square01_monomial_integral ( int e[2] );
double *square01_sample ( int n, int &seed );
double squaresym_area ( );
double squaresym_monomial_integral ( int e[2] );
double *squaresym_sample ( int n, int &seed );
void timestamp ( );
